name: Node Speed Test

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: '>=1.17.0'
          check-latest: true
      - run: go install github.com/jon96/clash-speedtest
      - run: clash-speedtest -c 'https://rvps.duckking.shop:26720/s/clashMeta/764ed3a1a918ee05994ba37a1340ca29'
      
