name: Node Speed Test

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: '>=1.17.0'
          check-latest: true
      - run: go build main.go
      - run: ./main -c "${{ secrets.SUBS_LINK }}" -output "info" -nf "@\d+(GBPS|Gbps|Mbps|MBPS)$" --size 20971520
      - name: Create/Update Gist
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh gist edit ${{ secrets.GIST_ID }} --add "proxies_info.yaml"
      
